/**
 * Lista de países con códigos ISO y nombres en español
 */
export interface Country {
  code: string;
  name: string;
}

export const COUNTRIES: Country[] = [
  { code: 'ES', name: 'España' },
  { code: 'VE', name: 'Venezuela' },
  { code: 'MX', name: 'México' },
  { code: 'AR', name: 'Argentina' },
  { code: 'CO', name: 'Colombia' },
  { code: 'CL', name: 'Chile' },
  { code: 'PE', name: 'Perú' },
  { code: 'EC', name: 'Ecuador' },
  { code: 'BO', name: 'Bolivia' },
  { code: 'PY', name: 'Paraguay' },
  { code: 'UY', name: 'Uruguay' },
  { code: 'CR', name: 'Costa Rica' },
  { code: 'PA', name: 'Panamá' },
  { code: 'GT', name: 'Guatemala' },
  { code: 'HN', name: 'Honduras' },
  { code: 'NI', name: 'Nicaragua' },
  { code: 'SV', name: 'El Salvador' },
  { code: 'DO', name: 'República Dominicana' },
  { code: 'CU', name: 'Cuba' },
  { code: 'PR', name: 'Puerto Rico' },
  { code: 'US', name: 'Estados Unidos' },
  { code: 'CA', name: 'Canadá' },
  { code: 'BR', name: 'Brasil' },
  { code: 'PT', name: 'Portugal' },
  { code: 'FR', name: 'Francia' },
  { code: 'IT', name: 'Italia' },
  { code: 'DE', name: 'Alemania' },
  { code: 'GB', name: 'Reino Unido' },
  { code: 'AU', name: 'Australia' },
  { code: 'NZ', name: 'Nueva Zelanda' },
  { code: 'JP', name: 'Japón' },
  { code: 'CN', name: 'China' },
  { code: 'IN', name: 'India' },
  { code: 'RU', name: 'Rusia' },
  { code: 'ZA', name: 'Sudáfrica' },
  { code: 'EG', name: 'Egipto' },
  { code: 'MA', name: 'Marruecos' },
  { code: 'AE', name: 'Emiratos Árabes Unidos' },
  { code: 'SA', name: 'Arabia Saudita' },
  { code: 'IL', name: 'Israel' },
  { code: 'TR', name: 'Turquía' },
  { code: 'KR', name: 'Corea del Sur' },
  { code: 'TH', name: 'Tailandia' },
  { code: 'PH', name: 'Filipinas' },
  { code: 'ID', name: 'Indonesia' },
  { code: 'MY', name: 'Malasia' },
  { code: 'SG', name: 'Singapur' },
  { code: 'VN', name: 'Vietnam' },
  { code: 'PL', name: 'Polonia' },
  { code: 'NL', name: 'Países Bajos' },
  { code: 'BE', name: 'Bélgica' },
  { code: 'CH', name: 'Suiza' },
  { code: 'AT', name: 'Austria' },
  { code: 'SE', name: 'Suecia' },
  { code: 'NO', name: 'Noruega' },
  { code: 'DK', name: 'Dinamarca' },
  { code: 'FI', name: 'Finlandia' },
  { code: 'IE', name: 'Irlanda' },
  { code: 'GR', name: 'Grecia' },
  { code: 'CZ', name: 'República Checa' },
  { code: 'HU', name: 'Hungría' },
  { code: 'RO', name: 'Rumania' },
  { code: 'BG', name: 'Bulgaria' },
  { code: 'HR', name: 'Croacia' },
  { code: 'RS', name: 'Serbia' },
  { code: 'UA', name: 'Ucrania' },
  { code: 'BY', name: 'Bielorrusia' },
  { code: 'KZ', name: 'Kazajstán' },
  { code: 'BD', name: 'Bangladesh' },
  { code: 'PK', name: 'Pakistán' },
  { code: 'AF', name: 'Afganistán' },
  { code: 'IR', name: 'Irán' },
  { code: 'IQ', name: 'Irak' },
  { code: 'SY', name: 'Siria' },
  { code: 'JO', name: 'Jordania' },
  { code: 'LB', name: 'Líbano' },
  { code: 'KW', name: 'Kuwait' },
  { code: 'QA', name: 'Catar' },
  { code: 'BH', name: 'Baréin' },
  { code: 'OM', name: 'Omán' },
  { code: 'YE', name: 'Yemen' },
  { code: 'LY', name: 'Libia' },
  { code: 'TN', name: 'Túnez' },
  { code: 'DZ', name: 'Argelia' },
  { code: 'SD', name: 'Sudán' },
  { code: 'ET', name: 'Etiopía' },
  { code: 'KE', name: 'Kenia' },
  { code: 'TZ', name: 'Tanzania' },
  { code: 'UG', name: 'Uganda' },
  { code: 'GH', name: 'Ghana' },
  { code: 'NG', name: 'Nigeria' },
  { code: 'SN', name: 'Senegal' },
  { code: 'CI', name: 'Costa de Marfil' },
  { code: 'CM', name: 'Camerún' },
  { code: 'AO', name: 'Angola' },
  { code: 'MZ', name: 'Mozambique' },
  { code: 'MW', name: 'Malaui' },
  { code: 'ZM', name: 'Zambia' },
  { code: 'ZW', name: 'Zimbabue' },
  { code: 'BW', name: 'Botsuana' },
  { code: 'NA', name: 'Namibia' },
  { code: 'LS', name: 'Lesoto' },
  { code: 'SZ', name: 'Suazilandia' },
  { code: 'MG', name: 'Madagascar' },
  { code: 'MU', name: 'Mauricio' },
  { code: 'SC', name: 'Seychelles' },
  { code: 'MV', name: 'Maldivas' },
  { code: 'LK', name: 'Sri Lanka' },
  { code: 'MM', name: 'Myanmar' },
  { code: 'KH', name: 'Camboya' },
  { code: 'LA', name: 'Laos' },
  { code: 'BN', name: 'Brunéi' },
  { code: 'TL', name: 'Timor Oriental' },
  { code: 'PG', name: 'Papúa Nueva Guinea' },
  { code: 'FJ', name: 'Fiyi' },
  { code: 'NC', name: 'Nueva Caledonia' },
  { code: 'PF', name: 'Polinesia Francesa' },
  { code: 'IS', name: 'Islandia' },
  { code: 'LU', name: 'Luxemburgo' },
  { code: 'MT', name: 'Malta' },
  { code: 'CY', name: 'Chipre' },
  { code: 'EE', name: 'Estonia' },
  { code: 'LV', name: 'Letonia' },
  { code: 'LT', name: 'Lituania' },
  { code: 'SK', name: 'Eslovaquia' },
  { code: 'SI', name: 'Eslovenia' },
  { code: 'MK', name: 'Macedonia del Norte' },
  { code: 'AL', name: 'Albania' },
  { code: 'BA', name: 'Bosnia y Herzegovina' },
  { code: 'ME', name: 'Montenegro' },
  { code: 'XK', name: 'Kosovo' },
  { code: 'MD', name: 'Moldavia' },
  { code: 'GE', name: 'Georgia' },
  { code: 'AM', name: 'Armenia' },
  { code: 'AZ', name: 'Azerbaiyán' },
  { code: 'TM', name: 'Turkmenistán' },
  { code: 'UZ', name: 'Uzbekistán' },
  { code: 'TJ', name: 'Tayikistán' },
  { code: 'KG', name: 'Kirguistán' },
  { code: 'MN', name: 'Mongolia' },
  { code: 'KP', name: 'Corea del Norte' },
  { code: 'TW', name: 'Taiwán' },
  { code: 'HK', name: 'Hong Kong' },
  { code: 'MO', name: 'Macao' },
  { code: 'NP', name: 'Nepal' },
  { code: 'BT', name: 'Bután' },
].sort((a, b) => a.name.localeCompare(b.name))

/**
 * Obtiene el nombre del país por su código ISO
 */
export function getCountryName(code: string): string | undefined {
  return COUNTRIES.find((c) => c.code === code)?.name
}

/**
 * Obtiene el código del país por su nombre
 */
export function getCountryCode(name: string): string | undefined {
  return COUNTRIES.find((c) => c.name === name)?.code
}

